namespace Network
{
	public enum eAPI
	{
		Invalid = 0,
		Login = 1,
		StageContinue = 2,
		StageReplay = 3,
		StageBegin = 4,
		S2 = 5,
		BuyJewel = 6,
		BuyCoin = 7,
		BuyHeart = 8,
		Recovary = 9,
		PlayerStar = 10,
		R1 = 11,
		BuyItem = 12,
		RegisterDeviceToken = 13,
		Roulette = 14,
		B1 = 15,
		BonusMultipleNum = 16,
		B2 = 17,
		DailyMissionCreate = 18,
		BonusStageStart = 19,
		BossStageContinue = 20,
		BuyItemBoss = 21,
		BossStageStart = 22,
		BS2 = 23,
		GachaStart = 24,
		AvatarLevelup = 25,
		AvatarSetWear = 26,
		GachaList = 27,
		GachaTop = 28,
		StageSkip = 29,
		CheckKey = 30,
		SetPayment = 31,
		CancelPayment = 32,
		MinilenSetWear = 33,
		ToastPromotionReward = 34,
		CollaboBBInfo = 35,
		MonetizationFreeAdReward = 36
	}
}
